export const Users = [
  {
    id: 1,
    profilePicture: "ASSETS/ksi.jpg",
    username: "Olajide Olatunji",
  },
  {
    id: 2,
    profilePicture: "ASSETS/simon.jpg",
    username: "Simon Minter",
  },
  {
    id: 3,
    profilePicture: "ASSETS/toby.jpg",
    username: "Tobi Brown",
  },
  {
    id: 4,
    profilePicture: "ASSETS/ethan.jpg",
    username: "Ethan Bazinga",
  },
  {
    id: 5,
    profilePicture: "ASSETS/p5.jpg",
    username: "Thomas Holden",
  },
  {
    id: 6,
    profilePicture: "ASSETS/p6.jpg",
    username: "Shirley Beauchamp",
  },
  {
    id: 7,
    profilePicture: "ASSETS/naruto.jpg",
    username: "Uzumaki Naruto",
  },
  {
    id: 8,
    profilePicture: "ASSETS/p2.jpg",
    username: "Janell Shrum",
  },
  {
    id: 9,
    profilePicture: "ASSETS/p3.jpg",
    username: "Alex Durden",
  },
  {
    id: 10,
    profilePicture: "ASSETS/p4.jpg",
    username: "Dora Hawks",
  },
];

export const Posts = [
  {
    id: 4,
    photo: "ASSETS/d10.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 1106,
    comment: 398,
  },
  {
    id: 1,
    photo: "ASSETS/d1.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 2,
    photo: "ASSETS/d8.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "ASSETS/d9.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },

  {
    id: 5,
    photo: "ASSETS/d5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    desc: "Love For All, Hatred For None.",
    photo: "ASSETS/d7.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "ASSETS/d6.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "ASSETS/d2.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "ASSETS/d3.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "ASSETS/d4.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
